---
# tasks file for ssmtp (Ubuntu specific)

- name: Install sSMTP packages
  apt:
    name: "{{ ssmtp_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  tags: ssmtp
